# Generated by Django 3.2.9 on 2022-01-29 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('surname', models.CharField(db_index=True, max_length=100)),
                ('lastname', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(db_index=True, max_length=100)),
                ('mail', models.CharField(db_index=True, max_length=100)),
                ('viber', models.CharField(db_index=True, max_length=100)),
                ('id_sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school.subject')),
            ],
        ),
        migrations.AddField(
            model_name='hometask',
            name='id_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school.classes'),
        ),
        migrations.AddField(
            model_name='hometask',
            name='id_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school.subject'),
        ),
        migrations.AddField(
            model_name='hometask',
            name='id_t',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school.teacher'),
        ),
    ]
