# Generated by Django 3.2.9 on 2022-02-01 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20220131_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('surname', models.CharField(db_index=True, max_length=100)),
                ('lastname', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(db_index=True, max_length=100)),
                ('mail', models.CharField(db_index=True, max_length=100)),
                ('id_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(null=True, upload_to='')),
                ('mark', models.IntegerField(null=True)),
                ('id_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school.student')),
                ('id_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school.hometask')),
            ],
        ),
    ]
