# Generated by Django 3.2.9 on 2022-06-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20220613_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
