# Generated by Django 3.2.9 on 2022-06-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_check_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometask',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
