# Generated by Django 3.2.9 on 2022-06-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_hometask_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check',
            options={'verbose_name': 'Выполненные задания', 'verbose_name_plural': 'Выполненные задания'},
        ),
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': 'Классы', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterModelOptions(
            name='hometask',
            options={'verbose_name': 'Домашние задания', 'verbose_name_plural': 'Домашние задания'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Ученики', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предметы', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Учителя', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Учителя', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.AddField(
            model_name='hometask',
            name='file',
            field=models.FileField(null=True, upload_to='upload/% Y/% m/% d/'),
        ),
    ]
